version: "3.0"

services:
  github-auth:
    container_name: github-auth-container
    image: github-auth:1.0.0
    restart: unless-stopped
    user: root
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - GITHUB_TRUST_STORE_PATH=""
      - GITHUB_TRUST_STORE_PASSWORD=""
      - GITHUB_API_VERSION=2022-11-28
      - GITHUB_CLIENT_TIMEOUT=100
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - APP_PORT=9090
    networks:
      - recruitment_task
networks:
  recruitment_task:
